# Generated by Django 4.2.23 on 2025-08-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=128)),
                ('sbp', models.IntegerField()),
                ('dbp', models.IntegerField()),
                ('hr', models.IntegerField(null=True)),
                ('timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user_id', 'timestamp'], name='measurement_user_id_1dd465_idx')],
            },
        ),
    ]
